name: Metrics Test
on:
  workflow_dispatch:
jobs:
  achievements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: all_achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: BenjaminHalko
          template: classic
          base: ""
          config_timezone: America/Vancouver
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
