name: Metrics
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  header:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: BenjaminHalko
          template: classic
          base: header
          config_timezone: America/Vancouver

  repositories:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: BenjaminHalko
          template: classic
          base: repositories
          config_timezone: America/Vancouver
          plugin_traffic: yes
          plugin_lines: yes

  activity_community:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: activity_community.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: BenjaminHalko
          template: classic
          base: activity, community
          config_timezone: America/Vancouver

  iso_calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: iso_calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: BenjaminHalko
          template: classic
          base: ""
          config_timezone: America/Vancouver
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: BenjaminHalko
          template: classic
          base: ""
          config_timezone: America/Vancouver
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_habits_trim: yes
    
  languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: langauges.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: BenjaminHalko
          template: classic
          base: ""
          config_timezone: America/Vancouver
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_ignored: yacc,java

  achievements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: langauges.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: BenjaminHalko
          template: classic
          base: ""
          config_timezone: America/Vancouver
          plugin_achievements: yes

  