name: Metrics
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
  push: {branches: "main"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: America/Vancouver
          plugin_achievements: yes
          plugin_code: yes
          plugin_code_visibility: public
          plugin_habits: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_ignored: yacc
          plugin_wakatime: yes
          plugin_wakatime_sections: time,languages,languages-graphs,editors
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}