name: Metrics
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: BenjaminHalko
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Vancouver
          plugin_achievements: yes
          plugin_code: yes
          plugin_code_visibility: public
          plugin_habits: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: bytes, percentage
          plugin_languages_ignored: yacc
          plugin_lines: yes
          plugin_traffic: yes
          plugin_wakatime: yes
          plugin_wakatime_days: 180
          plugin_wakatime_limit: 15
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_repositories_visibility: public
