name: Metrics
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: BenjaminHalko
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header,activity,community,repositories,metadata
          config_timezone: America/Vancouver
          plugin_code: yes
          plugin_code_visibility: public
          plugin_habits: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_ignored: yacc,java
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_types: commit,pull_request
          plugin_traffic: yes
          plugin_wakatime: yes
          plugin_wakatime_days: 180
          plugin_wakatime_limit: 15
          plugin_wakatime_sections: time,languages,languages-graphs,editors
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
