name: Metrics
on:
  workflow_dispatch:
jobs:
  habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: BenjaminHalko
          template: classic
          base: ""
          config_timezone: America/Vancouver
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_habits_trim: yes
